# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_auto_20151212_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='lat',
            field=models.DecimalField(decimal_places=24, default=0, max_digits=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stop',
            name='lon',
            field=models.DecimalField(decimal_places=24, default=0, max_digits=32),
            preserve_default=False,
        ),
    ]
