# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_auto_20151212_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='agency',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='transport.Agency'),
        ),
        migrations.AlterField(
            model_name='route',
            name='agency',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='transport.Agency'),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='stop',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='transport.Stop'),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='trip',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='transport.Trip'),
        ),
    ]
